from . import vehicle_brand
from . import vehicle_service
from . import vehicle_model
from . import vehicle_type
from . import vehicle_vehicle
from . import vehicle_integration
from . import vehicle_integration_status
from . import vehicle_integration_log
from . import res_partner
