{
    'name': 'Vehículos',
    'version': '1.0',
    'category': 'Services/Vehículos',
    'sequence': 40,
    'summary': 'Registro e integración de vehículos',
    'depends': [
        'base',
        'contacts',
        'mail',
    ],
    'data': [
        'security/vehicle_security.xml',
        'security/ir.model.access.csv',
        'data/ir_actions_server_data.xml',
        'data/ir_sequence_data.xml',
        'data/vehicle_brand_data.xml',
        'data/vehicle_type_data.xml',
        'data/vehicle_service_data.xml',
        'data/vehicle_model_data.xml',
        'views/vehicle_menus.xml',
        'views/vehicle_brand_views.xml',
        'views/vehicle_service_views.xml',
        'views/vehicle_integration_views.xml',
        'views/vehicle_integration_log_views.xml',
        'views/vehicle_model_views.xml',
        'views/vehicle_type_views.xml',
        'views/vehicle_vehicle_views.xml',
        'views/res_partner_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'vehicle/static/src/**/*',
        ],
    },
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
